## Importing Modules

In [1]:
import pandas as pd

## EDA Data

In [2]:
df = pd.read_csv("SuperStore_Sales_Dataset.csv")

In [3]:
df.head()

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode,ind1,ind2
0,4918,CA-2019-160304,01-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.94,1,28.2668,NaN,Online,NaN,NaN
1,4919,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.94,3,38.2668,NaN,Online,NaN,NaN
2,4920,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Technology,Phones,GE 30522EE2,231.98,2,67.2742,NaN,Cards,NaN,NaN
3,3074,CA-2019-125206,03-01-2019,05-01-2019,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,...,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.46,2,28.6150,NaN,Online,NaN,NaN
4,8604,US-2019-116365,03-01-2019,08-01-2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.08,2,-5.2640,NaN,Online,NaN,NaN

In [4]:
df.tail()

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode,ind1,ind2
5896,907,CA-2020-143259,30-12-2020,03-01-2021,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Fully Ass...",213.136,4,12.1176,NaN,COD,NaN,NaN
5897,1297,CA-2020-115427,30-12-2020,03-01-2021,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",295.904,2,4.5188,1.0,Online,NaN,NaN
5898,5092,CA-2020-156720,30-12-2020,03-01-2021,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,Office Supplies,Fasteners,Bagged Rubber Bands,388.024,3,-0.6048,NaN,Online,NaN,NaN
5899,909,CA-2020-143259,30-12-2020,03-01-2021,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,462.776,3,19.7910,NaN,COD,NaN,NaN
5900,5093,CA-2020-151450,31-12-2020,04-01-2021,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,Office Supplies,Fasteners,Bagged Rubber Bands,2975.510,3,-0.6048,NaN,COD,NaN,NaN

In [5]:
df.shape

(5901, 23)

In [6]:
df.size

135723

In [7]:
df.dtypes

Row ID+O6G3A1:R6      int64
Order ID             object
Order Date           object
Ship Date            object
Ship Mode            object
Customer ID          object
Customer Name        object
Segment              object
Country              object
City                 object
State                object
Region               object
Product ID           object
Category             object
Sub-Category         object
Product Name         object
Sales               float64
Quantity              int64
Profit              float64
Returns             float64
Payment Mode         object
ind1                float64
ind2                float64
dtype: object

In [8]:
df.isna().sum()

Row ID+O6G3A1:R6       0
Order ID               0
Order Date             0
Ship Date              0
Ship Mode              0
Customer ID            0
Customer Name          0
Segment                0
Country                0
City                   0
State                  0
Region                 0
Product ID             0
Category               0
Sub-Category           0
Product Name           0
Sales                  0
Quantity               0
Profit                 0
Returns             5614
Payment Mode           0
ind1                5901
ind2                5901
dtype: int64

In [10]:
df.sample(5)

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode,ind1,ind2
4450,8045,CA-2020-165008,15-09-2020,17-09-2020,Second Class,DO-13645,Doug O'Connell,Consumer,United States,Salt Lake City,...,Office Supplies,Binders,"Avery Trapezoid Ring Binder, 3"" Capacity, Blac...",317.056,9,106.9578,1.0,COD,NaN,NaN
4693,752,CA-2020-126074,02-10-2020,06-10-2020,Standard Class,RF-19735,Roland Fjeld,Consumer,United States,Trenton,...,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,106.980,7,22.7920,NaN,Online,NaN,NaN
1282,5604,CA-2019-117919,27-08-2019,29-08-2019,Second Class,TB-21355,Todd Boyes,Corporate,United States,Houston,...,Office Supplies,Paper,Southworth 25% Cotton Premium Laser Paper and ...,79.920,5,27.9720,NaN,COD,NaN,NaN
1068,1527,CA-2019-122392,22-07-2019,27-07-2019,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Allentown,...,Office Supplies,Art,12 Colored Short Pencils,4.160,2,0.3640,NaN,COD,NaN,NaN
4324,4153,CA-2020-100160,07-09-2020,11-09-2020,Standard Class,CB-12025,Cassandra Brandow,Consumer,United States,Philadelphia,...,Office Supplies,Paper,"Eureka Recycled Copy Paper 8 1/2"" x 11"", Ream",93.552,3,5.4432,NaN,Online,NaN,NaN

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5901 entries, 0 to 5900
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row ID+O6G3A1:R6  5901 non-null   int64
 1   Order ID          5901 non-null   object
 2   Order Date        5901 non-null   object
 3   Ship Date         5901 non-null   object
 4   Ship Mode         5901 non-null   object
 5   Customer ID       5901 non-null   object
 6   Customer Name     5901 non-null   object
 7   Segment           5901 non-null   object
 8   Country           5901 non-null   object
 9   City              5901 non-null   object
 10  State             5901 non-null   object
 11  Region            5901 non-null   object
 12  Product ID        5901 non-null   object
 13  Category          5901 non-null   object
 14  Sub-Category      5901 non-null   object
 15  Product Name      5901 non-null   object
 16  Sales             5901 non-null   float64
 17  Quantity          5901 non-null   int64
 18  Profit            5901 non-null   float64
 19  Returns           287 non-null    float64
 20  Payment Mode      5901 non-null   object
 21  ind1              0 non-null      float64
 22  ind2              0 non-null      float64
dtypes: float64(5), int64(2), object(16)
memory usage: 1.0+ MB

In [12]:
df.index

RangeIndex(start=0, stop=5901, step=1)

In [13]:
df.columns

Index(['Row ID+O6G3A1:R6', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Profit', 'Returns', 'Payment Mode', 'ind1',
       'ind2'],
      dtype='object')

In [14]:
df.describe()

,Row ID+O6G3A1:R6,Sales,Quantity,Profit,Returns,ind1,ind2
count,5901.000000,5901.000000,5901.000000,5901.000000,287.0,0.0,0.0
mean,5022.422471,265.345589,3.781901,29.700408,1.0,NaN,NaN
std,2877.977184,474.260645,2.212917,259.589138,0.0,NaN,NaN
min,1.000000,0.836000,1.000000,-6599.978000,1.0,NaN,NaN
25%,2486.000000,71.976000,2.000000,1.795500,1.0,NaN,NaN
50%,5091.000000,128.648000,3.000000,8.502500,1.0,NaN,NaN
75%,7456.000000,265.170000,5.000000,28.615000,1.0,NaN,NaN
max,9994.000000,9099.930000,14.000000,8399.976000,1.0,NaN,NaN

In [15]:
df.min()

Row ID+O6G3A1:R6                                                    1
Order ID                                               CA-2019-100041
Order Date                                                 01-01-2019
Ship Date                                                  01-01-2020
Ship Mode                                                 First Class
Customer ID                                                  AA-10315
Customer Name                                           Aaron Bergman
Segment                                                      Consumer
Country                                                 United States
City                                                         Aberdeen
State                                                         Alabama
Region                                                        Central
Product ID                                            FUR-BO-10000112
Category                                                    Furniture
Sub-Category                                              Accessories
Product Name        "While you Were Out" Message Book, One Form pe...
Sales                                                           0.836
Quantity                                                            1
Profit                                                      -6599.978
Returns                                                           1.0
Payment Mode                                                      COD
ind1                                                              NaN
ind2                                                              NaN
dtype: object

In [16]:
df.max()

Row ID+O6G3A1:R6                                  9994
Order ID                                US-2020-169551
Order Date                                  31-12-2020
Ship Date                                   31-12-2020
Ship Mode                               Standard Class
Customer ID                                   ZD-21925
Customer Name                       Zuschuss Donatelli
Segment                                    Home Office
Country                                  United States
City                                              Yuma
State                                          Wyoming
Region                                            West
Product ID                             TEC-PH-10004977
Category                                    Technology
Sub-Category                                    Tables
Product Name        netTALK DUO VoIP Telephone Service
Sales                                          9099.93
Quantity                                            14
Profit                                        8399.976
Returns                                            1.0
Payment Mode                                    Online
ind1                                               NaN
ind2                                               NaN
dtype: object

## Cleaning And Transforming Data

In [18]:
df["Returns"] = df["Returns"].fillna(0)

In [19]:
df = df.drop(columns=["ind1", "ind2"])

In [20]:
df["Sales"] = df["Sales"].astype('int')

In [21]:
df["Returns"] = df["Returns"].astype('int')

In [24]:
df.rename(columns={
    "Row ID+O6G3A1:R6": "Row_ID_O6G3A1_R6",
    "Order ID": "Order_ID",
    "Order Date": "Order_Date",
    "Ship Date": "Ship_Date",
    "Ship Mode": "Ship_Mode",
    "Customer ID": "Customer_ID",
    "Customer Name": "Customer_Name",
    "Sub-Category": "Sub_Category",
    "Payment Mode": "Payment_Mode"}, inplace=True)

In [25]:
df.columns

Index(['Row_ID_O6G3A1_R6', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode',
       'Customer_ID', 'Customer_Name', 'Segment', 'Country', 'City', 'State',
       'Region', 'Product ID', 'Category', 'Sub_Category', 'Product Name',
       'Sales', 'Quantity', 'Profit', 'Returns', 'Payment_Mode'],
      dtype='object')

## Business Questions

## 1. Highest Sales and Profit by Category

In [27]:
Highest_Sales_by_Category = df.groupby("Category")["Sales"].sum()
Highest_Sales_by_Category

Category
Furniture          450796
Office Supplies    641724
Technology         469815
Name: Sales, dtype: int64

# 2. Sales and Profit by State

In [30]:
sales_profit_by_state = df.groupby("State")[["Sales", "Profit"]].sum()
sales_profit_by_state.head()

             Sales      Profit
State
Alabama      11865   3336.3075
Arizona      22844  -2761.1100
Arkansas      9626   1873.9949
California  334481  49372.1750
Colorado     29188  -5825.5857

# 3. Sales and Profit by City

In [32]:
sales_profit_by_city = df.groupby("City")[["Sales", "Profit"]].sum()
sales_profit_by_city.head()

             Sales    Profit
City
Aberdeen       107    6.6300
Abilene        360   -3.7584
Akron         2749  -98.7128
Albuquerque   2430  496.5406
Alexandria     219   24.7100

# 4. Sales and Profit by Customer Segment

In [33]:
sales_profit_by_segment = df.groupby("Segment")[["Sales", "Profit"]].sum()
sales_profit_by_segment

              Sales      Profit
Segment
Consumer     751246  81338.5875
Corporate    508694  57805.7991
Home Office  302395  36117.7193

# 5. Monthly Sales Trend

In [41]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"], format="%d-%m-%Y") 
monthly_sales = df.groupby(df["Order_Date"].dt.to_period("M"))["Sales"].sum()
monthly_sales.head()

Order_Date
2019-01    18564
2019-02    19926
2019-03    51619
2019-04    38648
2019-05    50860
Freq: M, Name: Sales, dtype: int64

# 6. Top Products by Sales and Profit

In [43]:
sales_profit_by_product = df.groupby("Product Name")[["Sales", "Profit"]].sum() 
sales_profit_by_product.head()

                                                    Sales    Profit
Product Name
"While you Were Out" Message Book, One Form per...    307   10.3880
#10 Gummed Flap White Envelopes, 100/Box              132   14.6202
#10 Self-Seal White Envelopes                         194   52.1230
#10 White Business Envelopes,4 1/8 x 9 1/2            531  145.2609
#10- 4 1/8" x 9 1/2" Recycled Envelopes               723   38.1938

# 7. Sales and Profit by Shipping Mode

In [44]:
sales_profit_by_ship_mode = df.groupby("Ship_Mode")[["Sales", "Profit"]].sum()
sales_profit_by_ship_mode

                 Sales      Profit
Ship_Mode
First Class     242362  29749.8665
Same Day         95759   8808.8243
Second Class    313841  36936.0265
Standard Class  910373  99767.3886

# 8. Sales and Quantity by Payment Mode

In [45]:
sales_quantity_by_payment_mode = df.groupby("Payment_Mode")[["Sales", "Quantity"]].sum() 
sales_quantity_by_payment_mode

               Sales  Quantity
Payment_Mode
COD           665971      9247
Cards         343633      4903
Online        552731      8167

# 9. Return Analysis by Category

In [47]:
returns_by_category = df.groupby("Category")[["Returns", "Profit"]].sum().round() 
returns_by_category

                 Returns   Profit
Category
Furniture             70  10007.0
Office Supplies      165  74797.0
Technology            52  90458.0

# 10. Top Customers by Sales and Profit

In [49]:
sales_profit_by_customer = df.groupby("Customer_Name")[["Sales", "Profit"]].sum() 
sales_profit_by_customer.head()

                 Sales     Profit
Customer_Name
Aaron Bergman      562   116.8680
Aaron Hawkins      428    40.3760
Aaron Smayling    3364  -285.8068
Adam Bellavance   8157  2045.8747
Adam Hart         3889   278.4494